# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-elephant-seal

# >> macros
# << macros

Summary:    Mastodon client
Version:    0.1
Release:    1
Group:      Applications/Internet
License:    GPLv3
URL:        https://github.com/SfietKonstantin/harbour-elephant-seal
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-elephant-seal.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  cmake
BuildRequires:  rust
BuildRequires:  rust-std-static
BuildRequires:  desktop-file-utils

%description
A simple Mastodon client


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
%ifarch %arm32
%define SB2_TARGET armv7-unknown-linux-gnueabihf
%endif
%ifarch %arm64
%define SB2_TARGET aarch64-unknown-linux-gnu
%endif
%ifarch %ix86
%define SB2_TARGET i686-unknown-linux-gnu
%endif

%ifnarch %ix86
export CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER=host-gcc
%endif

export CARGO_BUILD_TARGET=%SB2_TARGET

%cmake -DRust_CARGO_TARGET=%SB2_TARGET .
make %{?_smp_mflags}
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
