name: Github CI build

on:
  pull_request:
    branches:
      - main
env:
  RELEASE: 4.5.0.16

jobs:
  build-sfos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE }}
        arch: i486

  build-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.2
        host: linux
        target: desktop
        arch: gcc_64
        dir: ${{ runner.temp }}
        setup-python: false
        aqtversion: ==3.1.*
        py7zrversion: ==0.20.*

    - name: Build
      run:  |
        cmake . -DCMAKE_BUILD_TYPE=Debug -DUSE_SHIM=ON
        make
